/* 
 The most codes are generated by AI (Chatgpt Pro)
  (1) Before everything began, I ask AI "What is Html, Css, JavaScript, and what 
    are the difference among them?" I learn about the basic code grammar and 
    introdution, so that I can continuous my following work successfully 
    and effectively.
  (2) I copy paste the descrption, grading rubric, and my scrach paper of 
    Project 1, open the deep thinking mode to give AI (Chatgpt) enough time to 
    generate the skeleton codes. It gave me three codes about html, js, and css.
  (3) I ask AI some details about the operations of git hub to run my code at my
    local computer to test.
  (4) To advance my code and achieve certain function, my strategy is giving AI a
    screen shoot and describing my requirments in much detail. After the codes
    generating, I roughly read the whole code and add them to my project. The
    following steps are debugging with AI help (Fortunately, no debugging during
    the process of my project)
  (5) Almost all codes are generated by AI (Chatgpt), in the collabration with AI,
    My core work is to mention some interesting functions and to advance 
    appearance (even no debugging in this project). 
*/

const root = document.documentElement;

function setTheme(theme) {
  if (theme === "light") root.classList.add("light");
  else root.classList.remove("light");
  localStorage.setItem("theme", theme);
}

function getSavedTheme() {
  return localStorage.getItem("theme") || "dark";
}

// Theme toggle
const themeToggle = document.getElementById("themeToggle");
setTheme(getSavedTheme());

themeToggle?.addEventListener("click", () => {
  const isLight = root.classList.contains("light");
  setTheme(isLight ? "dark" : "light");
});

// Mobile nav toggle
const navToggle = document.querySelector(".nav-toggle");
const navLinks = document.getElementById("nav-links");

navToggle?.addEventListener("click", () => {
  const isOpen = navLinks.classList.toggle("open");
  navToggle.setAttribute("aria-expanded", String(isOpen));
});

// Close mobile menu after clicking a link
navLinks?.addEventListener("click", (e) => {
  const target = e.target;
  if (target instanceof HTMLAnchorElement) {
    navLinks.classList.remove("open");
    navToggle?.setAttribute("aria-expanded", "false");
  }
});

// Footer year
const yearEl = document.getElementById("year");
if (yearEl) yearEl.textContent = String(new Date().getFullYear());

// Simple client-side form validation (no backend)
const form = document.getElementById("contactForm");
const statusEl = document.getElementById("formStatus");

form?.addEventListener("submit", (e) => {
  e.preventDefault();

  const formData = new FormData(form);
  const name = String(formData.get("name") || "").trim();
  const email = String(formData.get("email") || "").trim();
  const message = String(formData.get("message") || "").trim();

  const emailOk = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);

  if (!name || !email || !message) {
    statusEl.textContent = "Please fill in all fields.";
    return;
  }
  if (!emailOk) {
    statusEl.textContent = "Please enter a valid email address.";
    return;
  }

  statusEl.textContent = "Looks good. (This demo only validates; it does not send.)";
  form.reset();
});

/*
AI generated: I describe a requirment that design a Easter egg about "self 
reference" when people click the "Link" of this project. AI gave me the code, 
and it works very well. I just changed some sentence. 
*/
// --- Easter egg: self-link + toast ---
const selfLink = document.getElementById("selfLink");
const toast = document.getElementById("toast");

const eggLines = [
  "Recursion!",
  "You are reading what you are reading!",
  "Self-reference detected. Proceed carefully!",
];

let toastTimer = null;

function showToast(message) {
  if (!toast) return;
  toast.textContent = message;
  toast.classList.add("show");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => toast.classList.remove("show"), 1600);
}

selfLink?.addEventListener("click", (e) => {
  e.preventDefault();

  window.scrollTo({ top: 0, behavior: "smooth" });

  const msg = eggLines[Math.floor(Math.random() * eggLines.length)];
  showToast(msg);

  history.replaceState(null, "", "#top");
});

/* AI generate for achieve a button to back the page top */
// Back to top button
const backToTopBtn = document.getElementById("backToTop");

// whether display the botton when scroling
window.addEventListener("scroll", () => {
  if (window.scrollY > 300) {
    backToTopBtn.classList.add("show");
  } else {
    backToTopBtn.classList.remove("show");
  }
});

// back to the page top after click the button
backToTopBtn.addEventListener("click", () => {
  window.scrollTo({
    top: 0,
    behavior: "smooth",
  });
});

